//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_TABLE
    {
        public System.Guid ID { get; set; }
        public System.Guid PROJECT_ID { get; set; }
        public int DATA_ORDER { get; set; }
        public string DATA_NAME { get; set; }
        public string DATA_TYPE { get; set; }
        public string DATA_OPTIONS { get; set; }
    }
}
